In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[111,112,113,114],[121,122,123,124],[131,132,133,134]],
    [[211,212,213,214],[221,222,223,224],[231,232,233,234]],
    [[311,312,313,314],[321,322,323,324],[331,332,333,334]],
])

In [3]:
escalar_t = escalar.T

AttributeError: 'float' object has no attribute 'T'

In [4]:
vector_t = vector.T
print(vector_t)

[3 4 5 6]


In [5]:
matriz_t = matriz.T

In [6]:
print(matriz_t)

[[1 3 5]
 [2 4 6]]


In [7]:
print(matriz.shape)

(3, 2)


In [8]:
print(matriz_t.shape)

(2, 3)


In [9]:
tensor_t = tensor.T
print(tensor_t)

[[[111 211 311]
  [121 221 321]
  [131 231 331]]

 [[112 212 312]
  [122 222 322]
  [132 232 332]]

 [[113 213 313]
  [123 223 323]
  [133 233 333]]

 [[114 214 314]
  [124 224 324]
  [134 234 334]]]


In [10]:
print(tensor)

[[[111 112 113 114]
  [121 122 123 124]
  [131 132 133 134]]

 [[211 212 213 214]
  [221 222 223 224]
  [231 232 233 234]]

 [[311 312 313 314]
  [321 322 323 324]
  [331 332 333 334]]]


In [11]:
matriz_t_t = matriz_t.T
print(matriz_t_t)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
print(matriz)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
A = matriz
B = matriz_t

In [14]:
C = A+B

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [15]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[6,5],[4,3],[2,1]])
C = A+B
print(A)
print(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[6 5]
 [4 3]
 [2 1]]
[[7 7]
 [7 7]
 [7 7]]


In [16]:
D = matriz + escalar
print(D)

[[ 6.679  7.679]
 [ 8.679  9.679]
 [10.679 11.679]]
